version: '3.8'

services:
  scammer-waste-bot:
    build: .
    ports:
      - "5001:5001"  # updated to match app.py port
    volumes:
      # mount analytics data for persistence
      - ./analytics_data:/app/analytics_data
      # mount logs if needed
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # optional: nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - scammer-waste-bot
    profiles:
      - production

networks:
  default:
    name: scammer-waste-bot-network
